### ISSUE TITLE
When the redis key that TTL has expired is decremented, this key is regenerating with its TTL of -1.

### ISSUE THREAD

**Issue by Nesrinasan** [spring-projects/spring-data-build#2023] opened 2023-06-13 20:59 UTC
Hi,
I want to talk about a situation I noticed about the decrement method.

I have a redis key that have 10sec TTL and value is 2. 
My case: 
1)The user is sent to redis cache with a TTL time of 10 seconds.
2)User calls a service and Service response takes more than 10 seconds and timeout is received.
3)however, since the TTL is 10 seconds, the user on the redis is also deleted when the timeout is taken from the service.
4)so, the value in the redis is desired to be reduced by one and the decrement method is called.
5)A new value with TTL value of -1 is sent to redis with the decrement method called for a key that is no longer in redis.
6)This causes problems with streams such as your rate limit.

I wrote a new method that is including a if condition to check if this key exists in redis. 

 **method** :

org.springframework.data.redis.core.DefaultValueOperations

@Override
	public Long decrementIfExist(K key) {

		V valueX = get(key);
		if(valueX != null){
			return decrement(key);
		}
		return -1l;
	}

**test of method**: 
org.springframework.data.redis.core.DefaultValueOperationsIntegrationTests

	@ParameterizedRedisTest 
	void testDecrementIfExist() {

		K key = keyFactory.instance();
		V value = valueFactory.instance();

		assumeThat(value).isInstanceOf(Long.class);

		valueOps.set(key, value);
		assertThat(valueOps.decrementIfExist(key)).isEqualTo(Long.valueOf((Long) value - 1));

		valueOps.getAndDelete(key);

		assertThat(valueOps.decrementIfExist(key)).isEqualTo(Long.valueOf((Long) value -1));
	}

If you let me, I want to add this method. Thanks.

**Comment by christophstrobl** [comment] 2023-06-14 07:13
duplicate of spring-projects/spring-data-redis#2607

**Closed by christophstrobl** 2023-06-14 07:13 UTC
Labels: status: waiting-for-triage
